<assignment>
<header>
<title>Titulo</title>
<proposition>Bla bla bla</proposition>
</header>
<initial>
<objects>
<objectsubstring>
<name>a</name>
<description>a</description>
<substring>a</substring>
</objectsubstring>
<objectsubstring>
<name>s</name>
<description>s</description>
<substring>s</substring>
</objectsubstring>
<objectsubstring>
<name>q</name>
<description>q</description>
<substring>q</substring>
</objectsubstring>
<objectsubstring>
<name>t</name>
<description>t</description>
<substring>t</substring>
</objectsubstring>
</objects>					
</initial>
<current/>
<expected/>
<modules>
<object_list>
<objects>
<objectsubstring>
<name>a</name>
<description>a</description>
<substring>a</substring>
</objectsubstring>
<objectsubstring>
<name>s</name>
<description>s</description>
<substring>s</substring>
</objectsubstring>
<objectsubstring>
<name>q</name>
<description>q</description>
<substring>q</substring>
</objectsubstring>
<objectsubstring>
<name>t</name>
<description>t</description>
<substring>t</substring>
</objectsubstring>
</objects>	
</object_list>
<history/>
<undo_redo/>
</modules>
<config>
<disablebutton1>Button1</disablebutton1>
<disablebutton2>Button2</disablebutton2>
</config>
<metadata>
<author>Danilo</author>
</metadata>
</assignment>