<header>
<title>Titulo<title>
<proposition>Bla bla bla</proposition>
</header>
<initial>
<object>Point1<object>
<object>Point2<object>
<object>Point3<object>
<object>Point4<object>
</initial>
<expected>
<object>Point5<object>
<object>Point6<object>
</expected>
<modules>
<objectlist>
<object>Point1<object>
<object>Point2<object>
<object>Point3<object>
<object>Point4<object>
</objectlist>
<history>
</history>
<undoredo>
</undoredo>
</modules>
<config>
<disablebuttons>
<button>Button1</button>
<button>Button2</button>
</disablebuttons>
</config>
<metadata>
<author>Danilo</author>
</metadata>